services:
  backend:
    build: .                          # [핵심] 현재 폴더(.)의 Dockerfile로 빌드하라는 뜻
    container_name: PlayType_Django     # 컨테이너 이름 지정
    volumes:
      - ./:/app                       # 로컬 코드 수정 시 컨테이너에 즉시 반영
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"                   # 포트 연결
    env_file:
      - .env
    environment:
      # 1. 호스트 주소 고정
      - POSTGRES_HOST=PlayType_db
    depends_on:
      - db
    networks:
      - app_network
    command: >                        # 서버 실행 명령어
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: PlayType_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: PlayType_redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  celery_worker:
      build: .                          # Django와 같은 이미지를 사용 (코드 공유)
      container_name: PlayType_Celery   # 컨테이너 이름
      command: celery -A config worker --loglevel=info  # Celery 실행 명령어
      volumes:
        - ./:/app                       # 코드 수정 시 반영
      env_file:
        - .env                          # 환경변수 파일 공유
      environment:
        - POSTGRES_HOST=PlayType_db     # DB 호스트 (backend와 동일하게 맞춤)
        - REDIS_URL=redis://redis:6379/0
      depends_on:
        - redis
        - db
      networks:
        - app_network
      restart: always                   # 죽으면 자동 재시작

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge